percolate/percolate-java-sdk

README.md
build.gradle
circle.yml
core/build.gradle
core/src/main/java/com/percolate/sdk/dto/ActivityStreamData.java
core/src/main/java/com/percolate/sdk/dto/Platform.java
settings.gradle

Using jitpack.io for maven setup.

jitpack setup

---

LICENSE.txt
README.md
android/build.gradle
android/src/main/java/com/percolate/sdk/android/dto/Terms.java
api/build.gradle
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/config/PercolateServer.java
api/src/main/java/com/percolate/sdk/api/request/terms/TermsParams.java
api/src/main/java/com/percolate/sdk/api/request/terms/TermsRequest.java
api/src/main/java/com/percolate/sdk/api/request/terms/TermsService.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitApiFactory.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitLogic.java
api/src/main/test/java/com/percolate/sdk/api/PercolateApiTest.java
core/src/main/java/com/percolate/sdk/dto/Terms.java
settings.gradle

- Created Added `api` module.
- API and Retrofit config setup.
- Created `terms` endpoint implementation.
- Added clone-style constructor to android Terms DTO.
- Updated README with API usage instructions.

API module

---

api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaGetParams.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaItemParams.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaListParams.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaRequest.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaService.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaUploadParams.java
api/src/main/java/com/percolate/sdk/api/request/media/release/MediaReleaseParams.java
api/src/main/java/com/percolate/sdk/api/request/media/release/MediaReleaseRequest.java
api/src/main/java/com/percolate/sdk/api/request/media/release/MediaReleaseService.java
api/src/test/fixtures/api/v3/media/GET.json
api/src/test/fixtures/api/v3/media/POST.json
api/src/test/fixtures/api/v3/media/folder:123/GET.json
api/src/test/fixtures/api/v3/media/folder:123/metadata/GET.json
api/src/test/fixtures/api/v3/media/video:123/GET.json
api/src/test/fixtures/api/v4/release/POST.json
api/src/test/java/com/percolate/sdk/api/request/media/MediaRequestTest.kt
api/src/test/java/com/percolate/sdk/api/request/media/release/MediaReleaseRequestTest.kt
core/src/main/java/com/percolate/sdk/enums/MediaType.java

**depends on PR #9**
3rd batch of network request endpoints.

API requests - batch 3

---

android/src/main/java/com/percolate/sdk/android/dto/Comment.java
android/src/main/java/com/percolate/sdk/android/dto/CommentContextExt.java
api/src/main/java/com/percolate/sdk/api/request/comment/CommentRequest.java
api/src/main/java/com/percolate/sdk/api/request/comment/CommentService.java
core/src/main/java/com/percolate/sdk/dto/Comment.java
core/src/main/java/com/percolate/sdk/dto/CommentContextExt.java
core/src/main/java/com/percolate/sdk/dto/CommentsInclude.java

- Added `delete` endpoint to comments service.
- Added `context_ext` field to comments object
- Fixed include json name "users" -> "user".

Comments service updates

---

api/build.gradle
python-bridge/build.gradle

Updated Retrofit and it's Jackson Converter to version 2.

Updated Retrofit to v2

---

android/src/main/java/com/percolate/sdk/android/dto/ChannelV5.java
core/src/main/java/com/percolate/sdk/dto/ChannelV5.java

Added platform extra to channel v5 dto.

Added Platform Extra to ChannelV5 DTO

---

android/src/main/java/com/percolate/sdk/android/dto/AuthTokenData.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizeData.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizeDataExt.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizePostData.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizePostDataExt.java
android/src/main/java/com/percolate/sdk/android/dto/SingleUser.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthRequest.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthService.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthTokenParams.java
core/src/main/java/com/percolate/sdk/dto/AuthTokenData.java
core/src/main/java/com/percolate/sdk/dto/AuthorizeData.java
core/src/main/java/com/percolate/sdk/dto/AuthorizeDataExt.java
core/src/main/java/com/percolate/sdk/dto/AuthorizePostData.java
core/src/main/java/com/percolate/sdk/dto/AuthorizePostDataExt.java
core/src/main/java/com/percolate/sdk/dto/SingleUser.java

Addition of objects required for OAuth2 API authentication.  `auth` module to add convenience methods for authentication is still TODO.

OAuth2 endpoints and DTOs

---

android/src/main/java/com/percolate/sdk/android/dto/AuthTokenData.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizeData.java
android/src/main/java/com/percolate/sdk/android/dto/AuthorizeDataExt.java
core/src/main/java/com/percolate/sdk/dto/AuthTokenData.java
core/src/main/java/com/percolate/sdk/dto/AuthorizeData.java
core/src/main/java/com/percolate/sdk/dto/AuthorizeDataExt.java

DTO Modifications for OAuth objects.

OAuth DTO changes

---

core/src/main/java/com/percolate/sdk/dto/License.java

Added equals/hashcode to License DTO

Added equals/hashcode to License DTO

---

android/src/main/java/com/percolate/sdk/android/dto/AuthTokenPostData.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthRequest.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthService.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaRequest.java
api/src/main/java/com/percolate/sdk/api/request/responses/CannedResponsesParams.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitApiFactory.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitLogic.java
core/src/main/java/com/percolate/sdk/dto/AuthTokenPostData.java

API updates required while performing Android app migration.

Param / Media request updates

---

android/src/main/java/com/percolate/sdk/android/dto/AuthTokenPostData.java
android/src/main/java/com/percolate/sdk/android/dto/Campaign.java
android/src/main/java/com/percolate/sdk/android/dto/Campaigns.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthRequest.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthService.java
api/src/main/java/com/percolate/sdk/api/request/campaigns/CampaignsParams.java
api/src/main/java/com/percolate/sdk/api/request/campaigns/CampaignsRequest.java
api/src/main/java/com/percolate/sdk/api/request/campaigns/CampaignsService.java
api/src/main/java/com/percolate/sdk/api/request/media/MediaRequest.java
api/src/main/java/com/percolate/sdk/api/request/responses/CannedResponsesParams.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitApiFactory.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitLogic.java
core/src/main/java/com/percolate/sdk/dto/AuthTokenPostData.java
core/src/main/java/com/percolate/sdk/dto/Campaign.java
core/src/main/java/com/percolate/sdk/dto/Campaigns.java

Campaigns endpoint

---

api/src/main/java/com/percolate/sdk/api/request/links/LinksRequest.java
api/src/main/java/com/percolate/sdk/api/request/links/LinksService.java

Invalid json body was being `POST`ed to `v3/links`.

Fix links POST request

---

README.md
auth/README.md
auth/build.gradle
auth/src/main/java/com/percolate/sdk/auth/AuthData.java
auth/src/main/java/com/percolate/sdk/auth/AuthErrorChecker.java
auth/src/main/java/com/percolate/sdk/auth/AuthNetworkRequests.java
auth/src/main/java/com/percolate/sdk/auth/AuthParamCreator.java
auth/src/main/java/com/percolate/sdk/auth/AuthResponse.java
auth/src/main/java/com/percolate/sdk/auth/AuthStatus.java
auth/src/main/java/com/percolate/sdk/auth/Authorize.java
auth/src/main/java/com/percolate/sdk/auth/JacksonUtils.java
auth/src/test/fixtures/auth.json
auth/src/test/fixtures/token.json
auth/src/test/java/com/percolate/sdk/auth/AuthErrorCheckerTest.kt
auth/src/test/java/com/percolate/sdk/auth/AuthIntegrationTest.kt
auth/src/test/java/com/percolate/sdk/auth/AuthParamCreatorTest.kt
auth/src/test/java/com/percolate/sdk/auth/JacksonUtilsTest.kt
settings.gradle

New `auth` module that provides convenience classes for performing OAuth2 authentication.

Auth module

---

api/src/main/java/com/percolate/sdk/api/request/platform/PlatformsParams.java

Added setters for `ids` and `types` to `PlatformsParams`.

Added ids and types field to get platforms request

---

android/src/main/java/com/percolate/sdk/android/dto/FacebookMentionV5Data.java
core/src/main/java/com/percolate/sdk/dto/FacebookMentionV5Data.java

New Facebook mentions object representation for V5 post data.

Facebook v5 mentions objects

---

api/src/main/java/com/percolate/sdk/api/request/followers/FollowersParams.java

Added limit of 1000 to followers request.

Added limit to followers request

---

android/src/main/java/com/percolate/sdk/android/dto/PostV5Include.java
core/src/main/java/com/percolate/sdk/dto/PostV5Data.java
core/src/main/java/com/percolate/sdk/dto/PostV5Include.java
core/src/main/java/com/percolate/sdk/enums/PostIncludeType.java

Add `include=schema_id` option to `v5/post` queries and related DTO updates.

Post schema include

---

core/src/main/java/com/percolate/sdk/dto/WorkspaceSection.java

Added `compareTo` to `WorkspaceSection` class to sort by ordinal.

Sort workspace sections

---

android/src/main/java/com/percolate/sdk/android/dto/Role.java
android/src/main/java/com/percolate/sdk/android/dto/Roles.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/roles/RolesParams.java
api/src/main/java/com/percolate/sdk/api/request/roles/RolesRequest.java
api/src/main/java/com/percolate/sdk/api/request/roles/RolesService.java
core/src/main/java/com/percolate/sdk/dto/Role.java
core/src/main/java/com/percolate/sdk/dto/Roles.java

Add `v5/role` endpoint and DTO's to SDK

User roles

---

core/src/main/java/com/percolate/sdk/enums/ActivityStreamType.java

1. Added `COMPLETE_POST_APPROVAL` to `isPostType` check. 
2. Added `COMPLETE_BRIEF_APPROVAL` and `COMPLETE_BRIEF_APPROVAL_STEP` to `isBriefSectionType`.

Added complete workflow stream types to check methods

---

api/src/main/java/com/percolate/sdk/api/request/preview/PreviewParams.java
api/src/main/java/com/percolate/sdk/api/request/preview/PreviewRequest.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/preview/PreviewRequestRx.java

Created `PreviewParams` class to pass in parameter to send as part of the POST request to create a preview.

Add preview request params

---

api/src/main/java/com/percolate/sdk/api/request/schema/SchemasListParams.java
core/src/main/java/com/percolate/sdk/enums/SchemaResourceType.java
core/src/main/java/com/percolate/sdk/enums/SchemaType.java

Added additional `v5/schema` API params.

New v5/schema API params

---

android/src/main/java/com/percolate/sdk/android/dto/MetadataItem.java
android/src/main/java/com/percolate/sdk/android/dto/MetadataList.java
android/src/main/java/com/percolate/sdk/android/dto/SingleMetadataItem.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/metadata/MetadataParams.java
api/src/main/java/com/percolate/sdk/api/request/metadata/MetadataRequest.java
api/src/main/java/com/percolate/sdk/api/request/metadata/MetadataService.java
api/src/test/fixtures/api/v5/metadata/123/GET.json
api/src/test/fixtures/api/v5/metadata/GET.json
api/src/test/fixtures/api/v5/metadata/POST.json
api/src/test/java/com/percolate/sdk/api/request/metadata/MetadataRequestTest.kt
core/src/main/java/com/percolate/sdk/dto/MetadataItem.java
core/src/main/java/com/percolate/sdk/dto/MetadataList.java
core/src/main/java/com/percolate/sdk/dto/SingleMetadataItem.java
rxjava/src/main/java/com/percolate/sdk/rxjava/PercolateApiRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/metadata/MetadataRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/metadata/MetadataServiceRx.java

Addition of `v5/metadata` endpoint.

New v5/metadata endpoint

---

android/src/main/java/com/percolate/sdk/android/dto/CampaignSectionData.java
core/src/main/java/com/percolate/sdk/dto/CampaignSectionData.java

Added comparator to campaign section.

Add sorting to campaign section

---

core/src/main/java/com/percolate/sdk/enums/PostStatus.java

Added new unpublish post status values.

Add unpublished status

---

android/src/main/java/com/percolate/sdk/android/dto/Media.java
core/src/main/java/com/percolate/sdk/dto/Media.java

Added getters and setters for file size in Media object.

Added file size field to media object

---

api/src/main/java/com/percolate/sdk/api/request/media/MediaListParams.java

Add `flat` param to media list request.

Add flat param media list request

---

core/src/main/java/com/percolate/sdk/enums/ApprovalType.java

Add `ASSET` to approval pool types enum.

Add asset approval pool type

---

android/src/main/java/com/percolate/sdk/android/dto/PostSetData.java
core/src/main/java/com/percolate/sdk/dto/PostSetData.java

Add `video_id` field to `PostSetData` DTO.

Add video_id field to post_set DTO

---

android/src/main/java/com/percolate/sdk/android/dto/Schema.java
android/src/main/java/com/percolate/sdk/android/dto/SchemaPlugin.java
core/src/main/java/com/percolate/sdk/dto/Schema.java
core/src/main/java/com/percolate/sdk/dto/SchemaPlugin.java

New `SchemaPlugin` objects on `Schema` object.

Added schema plugin objects to SDK

---

android/src/main/java/com/percolate/sdk/android/dto/AutocompleteResponse.java
android/src/main/java/com/percolate/sdk/android/dto/AutocompleteResponseData.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/autocomplete/AutocompleteParams.java
api/src/main/java/com/percolate/sdk/api/request/autocomplete/AutocompleteRequest.java
api/src/main/java/com/percolate/sdk/api/request/autocomplete/AutocompleteService.java
api/src/test/fixtures/api/v5/autocomplete/GET.json
api/src/test/java/com/percolate/sdk/api/request/autocomplete/AutocompleteRequestTest.kt
core/src/main/java/com/percolate/sdk/dto/AutocompleteResponse.java
core/src/main/java/com/percolate/sdk/dto/AutocompleteResponseData.java
rxjava/src/main/java/com/percolate/sdk/rxjava/PercolateApiRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/autocomplete/AutocompleteRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/autocomplete/AutocompleteServiceRx.java

Add objects to support `v5/autocomplete/` endpoint.

Added v5/autocomplete/ endpoint support

---

android/src/main/java/com/percolate/sdk/android/dto/Schema.java
android/src/main/java/com/percolate/sdk/android/dto/VersionData.java
core/src/main/java/com/percolate/sdk/dto/Schema.java
core/src/main/java/com/percolate/sdk/dto/VersionData.java

Add new fields to `Schema` DTO object.

Add additional fields to schema DTO object

---

android/src/main/java/com/percolate/sdk/android/dto/CustomMediaMetaData.java
android/src/main/java/com/percolate/sdk/android/dto/Media.java
core/src/main/java/com/percolate/sdk/dto/CustomMediaMetaData.java
core/src/main/java/com/percolate/sdk/dto/Media.java

Added custom metadata field to Media object.

Added Metadata field to Media object

---

api/src/main/java/com/percolate/sdk/api/request/users/UsersService.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/users/UsersServiceRx.java

Updated the endpoint `/v5/user/{user_id}/password` to use `@Body` rather than `@QueryMap`.

Update Password Endpoint Definition

---

api/src/main/java/com/percolate/sdk/api/request/campaign/CampaignsListParams.java

Added 
- start_at:from
- end_at:to
- approval_workflow
params for filtering campaigns.

Add Filtering Params for Campaigns Request

---

android/src/main/java/com/percolate/sdk/android/dto/PostAttachment.java
android/src/main/java/com/percolate/sdk/android/dto/PostAttachmentData.java
android/src/main/java/com/percolate/sdk/android/dto/SinglePostAttachment.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/post_attachment/PostAttachmentParams.java
api/src/main/java/com/percolate/sdk/api/request/post_attachment/PostAttachmentRequest.java
api/src/main/java/com/percolate/sdk/api/request/post_attachment/PostAttachmentService.java
api/src/test/fixtures/api/v5/post_attachment/123/GET.json
api/src/test/fixtures/api/v5/post_attachment/123/PUT.json
api/src/test/fixtures/api/v5/post_attachment/GET.json
api/src/test/fixtures/api/v5/post_attachment/POST.json
api/src/test/java/com/percolate/sdk/api/request/post_attachment/PostAttachmentRequestTest.kt
core/src/main/java/com/percolate/sdk/dto/PostAttachment.java
core/src/main/java/com/percolate/sdk/dto/PostAttachmentData.java
core/src/main/java/com/percolate/sdk/dto/SinglePostAttachment.java
rxjava/src/main/java/com/percolate/sdk/rxjava/PercolateApiRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/post_attachment/PostAttachmentRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/post_attachment/PostAttachmentServiceRx.java

Added get, create and update requests for post attachments.

Add Post Attachment Requets

---

android/src/main/java/com/percolate/sdk/android/dto/PostV5Data.java
core/src/main/java/com/percolate/sdk/dto/PostV5Data.java
core/src/main/java/com/percolate/sdk/enums/SchemaType.java

- added v5 `post.post_attachment_ids` field.
- added `post_attachment` API value for schema `type` query.

Post Attachment Changes

---

api/src/main/java/com/percolate/sdk/api/request/features/FeaturesParams.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/config/ConfigRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/config/ConfigServiceRx.java

This PR also fixes an invalid return type declared on the Config endpoint.

Add scope_ids & limit params to features endpoint

---

android/src/main/java/com/percolate/sdk/android/dto/Preference.java
android/src/main/java/com/percolate/sdk/android/dto/PreferenceData.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/preference/PreferenceParams.java
api/src/main/java/com/percolate/sdk/api/request/preference/PreferenceRequest.java
api/src/main/java/com/percolate/sdk/api/request/preference/PreferenceService.java
api/src/test/fixtures/api/v5/preference/GET.json
api/src/test/java/com/percolate/sdk/api/request/preference/PreferenceRequestTest.kt
core/src/main/java/com/percolate/sdk/dto/Preference.java
core/src/main/java/com/percolate/sdk/dto/PreferenceData.java
rxjava/src/main/java/com/percolate/sdk/rxjava/PercolateApiRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/preference/PreferenceRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/preference/PreferenceServiceRx.java

Add preference request

---

api/src/main/java/com/percolate/sdk/api/request/channel/ChannelParams.java

Add `include` param to the `ChannelsParams`.

Add include param to the channels request

---

android/src/main/java/com/percolate/sdk/android/dto/ChannelsInclude.java
core/src/main/java/com/percolate/sdk/dto/ChannelsInclude.java

Create `ChannelsInclude` and include it in `Channels` DTO.

Add include field to the Channels

---

core/src/main/java/com/percolate/sdk/dto/Channels.java

Add getter and setter for `ChannelsInclude`.

Add getter and setter for channels include

---

api/src/main/java/com/percolate/sdk/api/request/post/PostListParams.java

Add `platform_ids` and `topic_ids` param to post request.

Add platform and topic param to post request

---

api/src/main/java/com/percolate/sdk/api/request/campaign/CampaignsListParams.java
core/src/main/java/com/percolate/sdk/enums/ApprovalWorkflowType.java

Add approval workflows type enum and update campaign lists params.

Add approval workflows type

---

api/src/main/java/com/percolate/sdk/api/request/preference/PreferenceParams.java
core/src/main/java/com/percolate/sdk/enums/PreferenceNameType.java

Add enum for preference names.

Add Preference Names Enum

---

android/src/main/java/com/percolate/sdk/android/dto/SingleFollower.java
api/src/main/java/com/percolate/sdk/api/request/followers/FollowersRequest.java
api/src/main/java/com/percolate/sdk/api/request/followers/FollowersService.java
api/src/test/fixtures/api/v4/follower/POST.json
api/src/test/java/com/percolate/sdk/api/request/followers/FollowersRequestTest.kt
core/src/main/java/com/percolate/sdk/dto/SingleFollower.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/followers/FollowersRequestRx.java
rxjava/src/main/java/com/percolate/sdk/rxjava/request/followers/FollowersServiceRx.java

Created `SingleFollower` as response of POST /v4/follower request.

Update POST follower response

---

api/src/main/java/com/percolate/sdk/api/request/post/PostListParams.java

Add `is_interaction=true|false` param for `v5/post` endpoint.

Add is_interaction param to v5/post

---

api/src/main/java/com/percolate/sdk/api/request/post/PostListParams.java

Add `live_at` to post list request.

Add live at param to post list request

---

android/src/main/java/com/percolate/sdk/android/dto/AuthTokenData.java
api/src/main/java/com/percolate/sdk/api/PercolateApi.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthRequest.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthService.java
api/src/main/java/com/percolate/sdk/api/request/auth/AuthTokenParams.java
auth/src/main/java/com/percolate/sdk/auth/AuthNetworkRequests.java
auth/src/test/fixtures/token.json
core/src/main/java/com/percolate/sdk/dto/AuthTokenData.java

Add authorization header with client id for /v5/token.

Updated params for v5/token

---

android/src/main/java/com/percolate/sdk/android/dto/Comment.java
core/src/main/java/com/percolate/sdk/dto/Comment.java

New `created_at` field added to `Comment` DTO object.

Add created_at field to Comment DTO

---

android/build.gradle
api/build.gradle
auth/build.gradle
build.gradle
circle.yml
core/build.gradle
gradle/wrapper/gradle-wrapper.properties
python-bridge/build.gradle
rxjava/build.gradle
settings.gradle

I updated also kotlin to the newest version.

DROID-650: Upgrade gradle to latest version.

---

api/build.gradle
api/src/main/java/com/percolate/sdk/api/utils/CompositeX509TrustManager.java
api/src/main/java/com/percolate/sdk/api/utils/PercolateTrustManagerBuilder.java
api/src/main/java/com/percolate/sdk/api/utils/RetrofitLogic.java

Fix for DROID:705 and DROID-717.

Fix for pinning of the certificates for *.percolate.com pattern

---

core/src/main/java/com/percolate/sdk/dto/UserRolesV5.java
core/src/main/java/com/percolate/sdk/utils/UserRolesUtils.java

After we merge this, we will have to release new version of percolate-java-sdk and bump the version for Android project.

DROID-769: App Crashing on Startup - fix.
